name: "build-test"
on:
  create:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout src
        uses: actions/checkout@v1
      - name: Create a release draft for a version
        id: create-release-draft
        uses: ./
      - name: Print the URL of the release draft
        run: echo ${{ steps.create-release-draft.outputs.release-url }} 